## Function MakeCacheMatrix
## Author: Keith Miller
## Version: 2.0
## Date: 17th February, 2015 : new version created to resubmit for the Signature Track. 
## Changes from v1.0 to v2.0.  clarified comments and corrected typos
## defines a list of 4 functions (methods) to be used to cache a matrix and the inverse of that matrix 

## 

makeCacheMatrix <- function(x = matrix()) {  ## accepts as input a square matrix to be inverted.  x is accessible using the get() function
        i <- NULL                            ## assigns i holds the inverted matrix.  i is only accessible using the getinverse() function 
        
        set <- function(y) {  ## first method "set", allows the stored matrix, x, to be overwritten with matrix y.  Not used in Programming Assignment 2  
                x <<- y       ## superassignment is used because x and i are variables in the parent environment
                i <<- NULL    ## inverse matrix set to NULL, indicating that it has to be calculated  
        }
        
        
        get <- function() x  ## returns the input matrix
        
        setinverse <- function(inverse) i <<- inverse  ## uses i to store the inverse matrix which is passed in "inverse".  Superassignment required as i
                                                        ## is a variable defined in parent environmentp$
        
        getinverse <- function() i  # returns the cached matrix in i
              
        
        
        list(set = set, get = get,  ##returns the list of functions to be called as methods of the object created by makeCacheMatrix a 
             setinverse = setinverse, ## and establishes "x" and "i" to hold the original matrix and its inverse respectively if it has been calculated
             getinverse = getinverse)  ## it does no calculation, it just stores and retrieves results and maintains those values in its parent frame
                                      ## i.e. its calling environment
}

## Function cacheSolve
## Author: Keith Miller
## Version: 2.0
## Date: 17th February, 2015 
## uses the object and functions created by running makeCacheMatrix against the input matrix to either calculate, cache and output the inverse matrix
##                              OR, if previously calculated, to retrieve the inverse matrix from its cache location in the object and output it   


cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of '...' using the object passed in x, which is a version of cacheMatrix.  
        ## cacheSolve accepts x, an object with 4 methods (set,get,setinverse, getinverse), 
        ## that was generated by the makeCacheMatrix function and exists to store
        ## 
        ## j holds the inverse matrix
        
        j <- x$getinverse()## if inverse exists then return it in j  
        if(!is.null(j)) {##if inverse has been calculated ie variable isnt NULL
                message("getting cached data")
                return(j) ##then print it out and stop
        }
        data <- x$get()  ## otherwise get the input matrix 
        j <- solve(data) ## calculate the inverse matrix  *** this line does the hard work of calculating the inverse
        x$setinverse(j)  ## store it in the cache object
        j}  #print inverse
